# 1.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

## Часть 1 (19 баллов)

1) Импортировать numpy и написать версию (1 балл)

In [118]:
import numpy as np
np.__version__

'1.18.1'

2) Создать нулевой вектор размера 10 (1 балл)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7 (2 балла)


In [9]:
np.full(7,7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100 включительно (2 балла)

In [19]:
arr4 = np.arange(101)[10:101]

In [21]:
arr4 = arr4[(arr4% 2 == 0)]

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

или

In [49]:
np.array([x for x in np.arange(101)[10:101] if x%2 == 0])

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд (4 балла)

In [62]:
np.random.random_sample(10)[::-1]

array([0.58940013, 0.41819378, 0.73583489, 0.53408626, 0.07682238,
       0.61570338, 0.15152332, 0.03496825, 0.55709984, 0.12220727])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9 (4 балла)

In [76]:
arr6 = np.arange(9).reshape((3,3))
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
print(arr6.shape)
print(arr6.ndim)

(3, 3)
2


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх. (5 баллов)

In [95]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

*если я праивльно понял слово "наверх"

## Часть 2 (26 баллов)

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки. (2 балла)

In [126]:
arr2_1 = np.diag(np.arange(1, 5))
arr2_1[arr2_1==0] = 7
arr2_1 

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках. (2 балла)

In [137]:
arr2_2 = np.zeros((5,5))
arr2_2 += np.arange(5)
arr2_2

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки (3 балла)

In [148]:
arr2_3 = np.random.rand(2,2)
arr2_3

array([[0.06010186, 0.71034621],
       [0.57250787, 0.14474772]])

In [149]:
arr2_3_means = arr2_3.mean(axis=1)
arr2_3_means

array([0.38522404, 0.35862779])

In [151]:
for index, value in np.ndenumerate(arr2_3):
    print(index, value)
    arr2_3[index,value] -= arr2_3_means[index]

(0, 0) 0.06010186476356194


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца (4 балла)

5) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7. (4 балла) 

6) Вектор чисел от 1 до 50 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  (6 баллов)

7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. (5 баллов)