# 1.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

## Часть 1 (19 баллов)

1) Импортировать numpy и написать версию (1 балл)

In [3]:
import numpy as np
np.__version__

'1.16.5'

2) Создать нулевой вектор размера 10 (1 балл)

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7 (2 балла)


In [9]:
np.full(7,7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100 включительно (2 балла)

In [5]:
np.arange(101)[10:101:2]

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд (4 балла)

In [62]:
np.random.random_sample(10)[::-1]

array([0.58940013, 0.41819378, 0.73583489, 0.53408626, 0.07682238,
       0.61570338, 0.15152332, 0.03496825, 0.55709984, 0.12220727])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9 (4 балла)

In [76]:
arr6 = np.arange(9).reshape((3,3))
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
print(arr6.shape)
print(arr6.ndim)

(3, 3)
2


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх. (5 баллов)

In [95]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

*если я праивльно понял слово "наверх"

## Часть 2 (26 баллов)

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки. (2 балла)

In [126]:
arr2_1 = np.diag(np.arange(1, 5))
arr2_1[arr2_1==0] = 7
arr2_1 

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках. (2 балла)

In [137]:
arr2_2 = np.zeros((5,5))
arr2_2 += np.arange(5)
arr2_2

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки (3 балла)

In [58]:
arr2_3 = np.random.rand(10,10)
arr2_3

array([[0.61843639, 0.4817219 , 0.62143632, 0.56296388, 0.2721931 ,
        0.78121816, 0.94771388, 0.94373682, 0.55706574, 0.31992763],
       [0.15203034, 0.51855058, 0.74417975, 0.02535837, 0.71961806,
        0.68933682, 0.07426305, 0.99247966, 0.9028693 , 0.71020029],
       [0.90697939, 0.9452469 , 0.40975418, 0.78251902, 0.3736779 ,
        0.59094751, 0.78885327, 0.02261908, 0.44312053, 0.67518327],
       [0.46692254, 0.27465613, 0.4448093 , 0.35324545, 0.74530673,
        0.25056814, 0.28772049, 0.67800308, 0.58361064, 0.57662608],
       [0.81021903, 0.33572789, 0.50165612, 0.80148866, 0.23816562,
        0.85832811, 0.91143767, 0.68155258, 0.14279099, 0.5582313 ],
       [0.01556858, 0.22572334, 0.02616058, 0.37327015, 0.17181777,
        0.52886615, 0.46817878, 0.27363539, 0.06384979, 0.66764601],
       [0.6689454 , 0.75560336, 0.31717061, 0.25252659, 0.86991786,
        0.92410714, 0.68134612, 0.13635946, 0.04819655, 0.48679462],
       [0.3603613 , 0.00412599, 0.6871837

In [59]:
arr2_3_means1 = arr2_3.mean(axis=1)
arr2_3_means1

array([0.61064138, 0.55288862, 0.59389011, 0.46614686, 0.5839598 ,
       0.28147165, 0.51409677, 0.47777752, 0.63703536, 0.48876287])

In [60]:
arr2_3_add_means = arr2_3
for index, value in np.ndenumerate(arr2_3):
    arr2_3_add_means[index] -= arr2_3_means1[index[0]]

arr2_3_add_means

array([[ 0.00779501, -0.12891948,  0.01079494, -0.04767751, -0.33844829,
         0.17057678,  0.33707249,  0.33309544, -0.05357564, -0.29071375],
       [-0.40085828, -0.03433804,  0.19129113, -0.52753025,  0.16672944,
         0.1364482 , -0.47862557,  0.43959104,  0.34998068,  0.15731167],
       [ 0.31308928,  0.3513568 , -0.18413592,  0.18862891, -0.2202122 ,
        -0.0029426 ,  0.19496316, -0.57127102, -0.15076958,  0.08129317],
       [ 0.00077568, -0.19149073, -0.02133756, -0.11290141,  0.27915987,
        -0.21557872, -0.17842637,  0.21185623,  0.11746379,  0.11047922],
       [ 0.22625923, -0.2482319 , -0.08230368,  0.21752886, -0.34579418,
         0.27436832,  0.32747787,  0.09759278, -0.4411688 , -0.0257285 ],
       [-0.26590307, -0.05574831, -0.25531108,  0.09179849, -0.10965388,
         0.24739449,  0.18670713, -0.00783626, -0.21762186,  0.38617435],
       [ 0.15484863,  0.24150658, -0.19692616, -0.26157018,  0.35582109,
         0.41001036,  0.16724935, -0.37773731

4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца (4 балла)

In [61]:
arr2_4 = np.random.rand(10,10)
arr2_4

array([[0.88657414, 0.62571815, 0.7776619 , 0.42618751, 0.83873721,
        0.03477251, 0.91429791, 0.07765895, 0.7682472 , 0.71687626],
       [0.05538975, 0.42238473, 0.04638411, 0.48166312, 0.19730865,
        0.48598809, 0.21399598, 0.33355484, 0.88271046, 0.62806095],
       [0.74581203, 0.14703226, 0.35515071, 0.36250994, 0.84295082,
        0.07988599, 0.69350011, 0.39902906, 0.36335551, 0.77161332],
       [0.89883245, 0.61453985, 0.0155679 , 0.12981679, 0.290038  ,
        0.41506172, 0.03428871, 0.3330952 , 0.16680383, 0.97276588],
       [0.18396128, 0.90157894, 0.46871028, 0.32475743, 0.17911327,
        0.64738439, 0.32392023, 0.40313146, 0.63866097, 0.91710168],
       [0.94061557, 0.50114798, 0.87611636, 0.81494299, 0.43700596,
        0.61198067, 0.84925458, 0.87877623, 0.74934787, 0.34977264],
       [0.7556665 , 0.63999106, 0.09876358, 0.84573243, 0.45422078,
        0.01636984, 0.9538524 , 0.52189559, 0.1988774 , 0.10263364],
       [0.42296962, 0.77446605, 0.4928428

In [62]:
arr2_4_med0 = np.median(arr2_4,axis=0)
arr2_4_med0

array([0.75073926, 0.620129  , 0.4119305 , 0.45392531, 0.37721428,
       0.45052491, 0.42839791, 0.40108026, 0.59416477, 0.59920313])

In [65]:
arr2_4_add_med = arr2_4
for index, value in np.ndenumerate(arr2_4):
    arr2_4_add_med[index] -= arr2_4_med0[index[1]]

arr2_4_add_med

array([[-1.36564366, -1.23466884, -0.45812959, -0.93558843, -0.29290562,
        -1.31680221, -0.37089581, -1.12558182, -1.01424712, -1.08073313],
       [-2.19682805, -1.43800226, -1.18940738, -0.88011283, -0.93433419,
        -0.86558663, -1.07119774, -0.86968593, -0.89978386, -1.16954845],
       [-1.50640576, -1.71335473, -0.88064077, -0.999266  , -0.28869202,
        -1.27168873, -0.59169361, -0.80421172, -1.4191388 , -1.02599608],
       [-1.35338534, -1.24584714, -1.22022359, -1.23195915, -0.84160484,
        -0.936513  , -1.25090501, -0.87014557, -1.61569049, -0.82484352],
       [-2.06825652, -0.95880804, -0.76708121, -1.03701851, -0.95252956,
        -0.70419033, -0.96127349, -0.80010932, -1.14383335, -0.88050772],
       [-1.31160223, -1.35923901, -0.35967513, -0.54683295, -0.69463687,
        -0.73959406, -0.43593914, -0.32446454, -1.03314645, -1.44783676],
       [-1.4965513 , -1.22039593, -1.1370279 , -0.51604351, -0.67742205,
        -1.33520488, -0.33134132, -0.68134518

5) Создать матрицу случайных чисел 5x5. Добавить к ней столбцы максимумов и минимумов по строкам. Получится матрица 5x7. (4 балла) 

In [66]:
arr2_5 = np.random.rand(5,5)
arr2_5

array([[0.88587879, 0.41575993, 0.866731  , 0.53679528, 0.72869357],
       [0.45216387, 0.63174967, 0.74226993, 0.69846119, 0.97337313],
       [0.06719117, 0.89208264, 0.42806185, 0.02294525, 0.1925574 ],
       [0.43665109, 0.62323316, 0.89780105, 0.22996844, 0.39086769],
       [0.33437898, 0.35033909, 0.29708661, 0.63985977, 0.13487828]])

In [85]:
arr2_5_maxmin = np.array([arr2_5.max(axis=1),arr2_5.min(axis=1)]).T
arr2_5_maxmin

array([[0.88587879, 0.41575993],
       [0.97337313, 0.45216387],
       [0.89208264, 0.02294525],
       [0.89780105, 0.22996844],
       [0.63985977, 0.13487828]])

In [90]:
arr2_5_add_maxmin = np.hstack((arr2_5,arr2_5_maxmin))
arr2_5_add_maxmin

array([[0.88587879, 0.41575993, 0.866731  , 0.53679528, 0.72869357,
        0.88587879, 0.41575993],
       [0.45216387, 0.63174967, 0.74226993, 0.69846119, 0.97337313,
        0.97337313, 0.45216387],
       [0.06719117, 0.89208264, 0.42806185, 0.02294525, 0.1925574 ,
        0.89208264, 0.02294525],
       [0.43665109, 0.62323316, 0.89780105, 0.22996844, 0.39086769,
        0.89780105, 0.22996844],
       [0.33437898, 0.35033909, 0.29708661, 0.63985977, 0.13487828,
        0.63985977, 0.13487828]])

In [91]:
arr2_5_add_maxmin.shape

(5, 7)

6) Вектор чисел от 1 до 50 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрицы. Найти произведение этих матриц. Найти обратную матрицу этого произведения.  (6 баллов)

In [107]:
arr2_6_even = np.arange(51)[2:51:2]
arr2_6_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [108]:
arr2_6_neven = np.arange(51)[1:50:2]
arr2_6_neven

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [142]:
arr2_6_even.reshape(25,1) * arr2_6_neven.reshape(1,25)

array([[   2,    6,   10,   14,   18,   22,   26,   30,   34,   38,   42,
          46,   50,   54,   58,   62,   66,   70,   74,   78,   82,   86,
          90,   94,   98],
       [   4,   12,   20,   28,   36,   44,   52,   60,   68,   76,   84,
          92,  100,  108,  116,  124,  132,  140,  148,  156,  164,  172,
         180,  188,  196],
       [   6,   18,   30,   42,   54,   66,   78,   90,  102,  114,  126,
         138,  150,  162,  174,  186,  198,  210,  222,  234,  246,  258,
         270,  282,  294],
       [   8,   24,   40,   56,   72,   88,  104,  120,  136,  152,  168,
         184,  200,  216,  232,  248,  264,  280,  296,  312,  328,  344,
         360,  376,  392],
       [  10,   30,   50,   70,   90,  110,  130,  150,  170,  190,  210,
         230,  250,  270,  290,  310,  330,  350,  370,  390,  410,  430,
         450,  470,  490],
       [  12,   36,   60,   84,  108,  132,  156,  180,  204,  228,  252,
         276,  300,  324,  348,  372,  396,  420,  

In [143]:
np.linalg.det(arr2_6_even.reshape(25,1) * arr2_6_neven.reshape(1,25))

0.0

Обратную матрицу можно найти только от квадратной матрицы, при этом детерминант не должен быть равен нулю. В нашем случае определитель от матрицы произведения равен 0, соответственно найти обатная матрица от произведения не существует.

7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. (5 баллов)

In [152]:
arr_2_7 = np.eye(8)
arr_2_7

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [202]:
def chess_square_matrix01 (dim):
    chess_matrix = np.eye(dim) #берем за основу единичную матрицу
    even_flag=False #Флаг четности
    for i,v in np.ndenumerate(chess_matrix):        
        if 0 == i[1]: #Если первый элемент строки, то инвертируем
            even_flag = not even_flag
        if chess_matrix[i] !=1: #Если уже 1 то пропускаем
            even_flag = not even_flag 
        else:
            if even_flag:
                chess_matrix[i] = 1
                even_flag =False            
            else:
                chess_matrix[i] = 0
                even_flag =True            
    return chess_matrix

In [205]:
chess_square_matrix01 (8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

или

In [189]:
np.tile(np.array([[1,0],[0,1]]), (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])